export const courses = [
	{
		faculty: 'Science',
		courses: ['Computer Science', 'Physical Science', 'Bio Science']
	},

	{
		faculty: 'Arts',
		courses: [
			'Arts in English',
			'Arts in Tamil',
			'Fine Arts in English',
			'Fine Arts in Tamil',
			'Law'
		]
	},

	{
		faculty: 'Management & Commerce',
		courses: ['Business Administartion', 'Commerce', 'Business Management']
	},

	{
		faculty: 'Medicine',
		courses: ['MBBS']
	},

	{
		faculty: 'Alied Health Science',
		courses: [
			'Medical Laboratory Science',
			'Nursing',
			'Pharmacy',
			'Sports Scince Unit'
		]
	},

	{
		faculty: 'Engineering',
		courses: [
			'Civil Engineering',
			'Computer Engineering',
			'Electrical & Electronic Engineering',
			'Interdisciplinary Studies'
		]
	},

	{
		faculty: 'Technologies',
		courses: [
			'Engineering Technology',
			'Bio Systems Technology',
			'Interdisciplinary Studies'
		]
	},

	{
		faculty: 'Agriculture',
		courses: [
			'Agronomy',
			'Animal Science',
			'Agricultural Biology',
			'Agricultural Chemistry',
			'Agricultural Engineering',
			'Agricultural Echonomics',
			'Auxiliary Core Courses',
			'Common Core Courses'
		]
	}
]

export const titles = ['Mr', 'Mrs', 'Miss', 'Rev']

export const districts = [
	{
		district: 'Kandy',
		DSDivisions: [
			{
				division: 'Thumpane',
				GSDivisions: [
					'Dehideniya',
					'Thahalpitiya',
					'Udahenepola',
					'Poholiyadda',
					'Etambegoda',
					'Minigamuwa',
					'Thennewela',
					'Minigamuwa Ihala',
					'Hiyadala Walpola',
					'Hiyadala',
					'Weththewa',
					'Hikgodawalpola',
					'Naranwala',
					'Galagedara',
					'Galagedara West',
					'Rockhill',
					'Akkarawatta',
					'Bonakot',
					'Haddapitiya',
					'Damunugasthenna',
					'Udalagama',
					'Delgasyaya',
					'Pethigewela',
					'Udapitiya',
					'Uduwa',
					'Poththila',
					'Kinigama East',
					'Kinigama',
					'Kaluwana',
					'Kannadeniya',
					'Gangodapitiya',
					'Pubbiliya',
					'Barandara',
					'Niyangoda',
					'Diyapalagoda',
					'Adungama Palkumbura',
					'Kandekumbura',
					'Ethamulla',
					'Ban Anga',
					'Kuragama',
					'Kuragama North',
					'Paranagama',
					'Galagedara Madige',
					'Galagedara Madige south',
					'Kobbegala',
					'Ambagahahena',
					'Gunadaha',
					'Opalla',
					'Meegahahena South',
					'Pallekotuwa',
					'Pavulpawa',
					'Kumburegama',
					'Alawattegama',
					'Namalthenna',
					'Marawanagoda',
					'Idamegama',
					'Henegama Palkumbura',
					'Medagoda Pahala',
					'Medagoda Ihala',
					'Kirindiwelpola',
					'Nikathenna',
					'Palukopiwatta',
					'Gallenawatta',
					'Galabawa',
					'Meegahahena',
					'Kandanhena East',
					'Niyambepola'
				]
			},
			{
				division: 'Poojapitiya',
				GSDivisions: [
					'Gallella',
					'Maruddana',
					'Harankahawa',
					'Henegama',
					'Ambaruppa',
					'Pathirada',
					'Molagoda',
					'Udahigulwala',
					'Udahena',
					'Siyapathgama',
					'Bokkawala',
					'Wewala',
					'Waldeniya',
					'Morankanda',
					'Wewala North',
					'Pahala Hingulwala',
					'Marathugoda North',
					'Marathugoda South',
					'Alagoda',
					'Madadeniya',
					'Warakadeniya',
					'Medagoda',
					'Ukgahakumbura',
					'Dombagammana',
					'Weligalla',
					'Rambukewala',
					'Dolapihilla North',
					'Dolapihilla South',
					'Kahatagasthenna',
					'Godahena',
					'Watagalathenna',
					'Galkanda',
					'Galhinna',
					'Kovila muduna',
					'Palliya Kotuwa',
					'Batagolladeniya',
					'Ihalamulla',
					'Dehiwatta',
					'Egodamulla South',
					'Egodamulla North',
					'Ankumbura South',
					'Ankumbura North',
					'Pahala Pallegama',
					'Uggala Janapadaya',
					'Ankumbura Udagama',
					'Welgala',
					'Alawatta',
					'Uda Kithulgolla',
					'Pahala Kithulgolla',
					'Watagoda',
					'Ovissa North',
					'Ovissa South',
					'Bamunupola',
					'Kiralagama',
					'Palipana',
					'Diddeniya',
					'Batagalla North',
					'Batagalla South',
					'Batugoda North',
					'Batugoda South',
					'Diwanawatta',
					'Mullegama South',
					'Mullegama North',
					'Kaluwana North',
					'Kaluwana South',
					'Kahawatta North',
					'Kahawatta South'
				]
			},
			{
				division: 'Akurana',
				GSDivisions: [
					'Bulugohothanna',
					'Kasawatta',
					'Udaweliketiya',
					'Pallewelikatiya',
					'Dodangolla',
					'Akurana',
					'Telambugahawatta Gama',
					'Waragashinna',
					'Neeralla',
					'Melchena',
					'Malwanahinna',
					'Kurugoda',
					'Hureegolla',
					'Delgasthenne',
					'Pangollamada',
					'Rathkoho',
					'Palledeegala',
					'Dunuvila North',
					'Dunuvila South',
					'Konakalagala',
					'Marahela',
					'Walahena',
					'Vilana Pallegama',
					'Kurudugahaela',
					'Uggala',
					'Malgamandeniya',
					'Dippitiya',
					'Mawathupola',
					'Arambepola',
					'Vilana Udagama',
					'Balakaduwa',
					'Delgasgoda',
					'Rambuke Ela',
					'Deegala',
					'Alawathugoda'
				]
			},
			{
				division: 'Pathadumbara',
				GSDivisions: [
					'Wattegama',
					'Wattegama North',
					'Gunembill',
					'Udurawana',
					'Doragamuwa',
					'Walpaladeniya',
					'Meegammana West',
					'Meegamawatta',
					'Kalugalawatta',
					'Galewatta',
					'Nawayalathenna',
					'Balanagala',
					'Galadeniya',
					'Pallethalavinna Ihala',
					'Millanga',
					'Megodagama',
					'Yatawara',
					'Yatawara Kandagama',
					'Ihala Yatawara',
					'Deegahawathura',
					'Mahakumbura',
					'Bogahakumbura',
					'Moonamale',
					'Ambathanna',
					'Kendaliyadda',
					'Girakaduwa',
					'Mandandawela',
					'Napana',
					'Hamindagoda',
					'Abasingama',
					'Leemagahadeniya',
					'Gunnepana Madige',
					'Madawala',
					'Yatirawana',
					'Walala',
					'Ketakahala',
					'Thalkotuwa',
					'Eriyagasthenna',
					'Puwakgahadeniya',
					'Meegammana',
					'Kahalla',
					'Polgolla',
					'Udathalavinna',
					'Pallethalavinna',
					'Udathalavinna Madige',
					'Egodagama',
					'Molagodayawatta',
					'Aluthgama',
					'Paranagama',
					'Madawala Madige',
					'Pihilladeniya',
					'Pitiyegedara'
				]
			},
			{
				division: 'Panvila',
				GSDivisions: [
					'Beddegama',
					'Angammana',
					'Thawalanthenna',
					'Gomaraya',
					'Hathale',
					'Arattana',
					'Panvila',
					'Udugoda',
					'Kelebokka',
					'Watakele',
					'Madulkele',
					'Kosgama',
					'Mahapathana',
					'Pitawala'
				]
			},
			{
				division: 'Udadumbara',
				GSDivisions: [
					'Pamunethenna',
					'Bamgarabedda East',
					'Bambarabedda West',
					'Devinnegama',
					'Ganegala',
					'Nugethenna West',
					'Nugethenna East',
					'Hunnasgiriya',
					'Denapitiya',
					'Halyala',
					'Mediriya',
					'Udadumbara',
					'Rambukwella West',
					'Rambukwella East',
					'Kiripattiya',
					'Mediwaka',
					'Karandagolla',
					'Godakumbura',
					'Gangoda',
					'Madugalla North',
					'Dewahandiya West',
					'Dumbaragama',
					'Pitigoda',
					'Kevulgama',
					'Minuwangamuwa',
					'Kalalgamuwa',
					'Madugalla Udagammedda',
					'Madugalla South',
					'Kalawala',
					'Dewahandiya East',
					'Hapukanda West',
					'Hapukanda East',
					'Udapitawala',
					'Pitawala',
					'Pitawala Udagammedda',
					'Mahawala',
					'Poppitiya',
					'Oyathenna',
					'Udakumbura',
					'Padupola',
					'Thalagune',
					'Gedaramada',
					'Kirigankumbura',
					'Pallewela',
					'Gerandigala',
					'Moonamalpelessa',
					'Hanwella',
					'Dambagahapitiya',
					'Andideniya',
					'Kalugaloya',
					'Udailuka',
					'Udawela',
					'Kandegama',
					'Wadawalakanda',
					'Kobonilla',
					'Pallekanda',
					'Meemure',
					'Kaikawala',
					'Kumbukgolla',
					'Karambaketiya',
					'Pusse Ela',
					'Kalugala',
					'Nawanagala'
				]
			},
			{
				division: 'Minipe',
				GSDivisions: [
					'Bebiya',
					'Kolonyaya',
					'Minipe',
					'Muttettuthenna',
					'Ambagahapelessa',
					'Asamodagamyaya',
					'Udayagala',
					'Batumulla',
					'Handaganawa',
					'Diyabubula',
					'Lunumadalaketiya',
					'Morayaya',
					'Weraganthota',
					'Bulathwelkandura',
					'Weragama',
					'Pallewatta',
					'Waragolla',
					'Gurulupotha',
					'Rathnella',
					'Mahaassedduma',
					'Hasalaka',
					'Welgala',
					'Mahagalahinna',
					'Keenapelessa',
					'Thorapitiya',
					'Welgahawadiya',
					'Mahayaya South',
					'Dambepitiya',
					'Ambagolla',
					'Udaththawa',
					'Udattawa North',
					'Udawela',
					'Kindigoda South',
					'Kindigoda North',
					'Wewere',
					'Palugolla',
					'Dehemigama',
					'Thotillagasella',
					'Himbutuwa',
					'Dambagahawela',
					'Pallegaladebokka',
					'Dungolla',
					'Galamuduna',
					'Udagaladebokka',
					'Ulpathagama',
					'Mahayaya North',
					'08 Ela',
					'Hasalaka Nagaraya'
				]
			},
			{
				division: 'Medadumbara',
				GSDivisions: [
					'Gonawala',
					'Kotaganga',
					'Thunisgala',
					'Galabodawatta',
					'Nagolla',
					'Elliyadda',
					'Galkotuwa',
					'Werapitiya',
					'Werathenna',
					'Bulathwatta',
					'Dunhinna',
					'Maneluwa',
					'Giddawa-Waradiwela',
					'Randiwela',
					'Weliketiya',
					'Putuhapuwa',
					'Giddawa',
					'Ambalagala',
					'Watapana',
					'Nugepathana',
					'Gangasirigama',
					'Madapola',
					'Karalliyadda',
					'Kandegama',
					'Vilamuna',
					'Randeniya',
					'Udawela',
					'Wellethota',
					'Rambukwella',
					'Rambukwella East',
					'Meegahamaditta',
					'Wegala',
					'Rangala',
					'Ranmulla',
					'Bobebila',
					'Duckwariya',
					'Makuldeniya',
					'Udispattuwa',
					'Godamunna',
					'Thangappuwa',
					'Siridigana',
					'Madeniyawaka',
					'Ferndail',
					'Pallebage',
					'Maharawela',
					'Birnside',
					'Gabbela',
					'Heeloya',
					'Kurukohogama',
					'Kiribattalawa',
					'Doraliyadda South',
					'Hakmana',
					'Retiyagama',
					'Nilgala',
					'Poddalgoda',
					'Kandekumbura',
					'Weladarada',
					'Metideniya',
					'Katugoda',
					'Hathiyalwela',
					'Rangala Aluthwatta',
					'Namadagala',
					'Welapahala',
					'Meda Gammedda',
					'Mangoda',
					'Udagammedda',
					'Nithulemada',
					'Maberiyathenna',
					'Rambukpotha',
					'Rajagala',
					'Senarathwela',
					'Wewegama',
					'Bomure',
					'Ellepola',
					'Medamahanuwara',
					'Udathenna',
					'Galambalama',
					'Hijrapura',
					'Moragahamula',
					'Ambagahalanda',
					'Wathuliyadda',
					'Mahadoraliyadda',
					'Ambale',
					'Meeriyagolla',
					'Sandasiri Dunuvila',
					'Puwakgahadiwela',
					'Thennalanda',
					'Bambaragahadeniya',
					'Meegahalanda',
					'Embalagama',
					'Amupitiya',
					'Udabage'
				]
			},
			{
				division: 'Kundasale',
				GSDivisions: [
					'Galpihilla',
					'Dunuhappawa',
					'Makkanigama',
					'Alawathugiriya gama',
					'Sirimalwatta East',
					'Sirimalwatte West',
					'Degaldoruwa',
					'Sirimalwatte Pallegama',
					'Karattamada',
					'Lewellagama',
					'Amunugama North',
					'Amunugama South',
					'Hapuwala',
					'Deekirimadawala',
					'Pilawala North',
					'Bogaskumbura',
					'Pilawala South',
					'Galapitambe',
					'Pallegunnepana North',
					'Pallegunnepana South',
					'Udagunnepana North',
					'Udagunnepana South',
					'Gabadagama South',
					'Gabadagama North',
					'Pallegama',
					'Wavinna',
					'Udagama North',
					'Udagama South',
					'Maharathenna East',
					'Maharathenna West',
					'Ihala Gonagama',
					'Hurikaduwa West',
					'Hurikaduwa North',
					'Hurikaduwa South',
					'Hurikaduwa East',
					'Nithulethenna',
					'Dodamgolla',
					'Galmaduwa',
					'Nattarampotha',
					'Arangala North',
					'Arangala South',
					'Mahawatta South',
					'Mahawatta West',
					'Mahawatta North',
					'Mahawatta East',
					'Kundasale North',
					'Kundasale South',
					'Wijaya Sri Gama',
					'Aluth Pallekele',
					'Ambakotewatta',
					'Rajawella North',
					'Rajawella South',
					'Balagolla East',
					'Balagolla West',
					'Kengalla',
					'Ihalawela',
					'Aswalapitiya',
					'Diyabubula',
					'Hurikaduwa Madige',
					'Manikhinna',
					'Dambarawa',
					'Hathamuna',
					'Delgaslanda',
					'Lunuketiyamaditta',
					'Deliwalathenna',
					'Heepitiya',
					'Malpana',
					'Galamuna',
					'Ahaspokuna North',
					'Ahaspokuna South',
					'Kumbukkandura North',
					'Kumbukkandura South',
					'Gonawala North',
					'Gonawala South',
					'Maluwegama',
					'Wepathana',
					'Kuruambemuduna',
					'Naranpanawa East',
					'Kandekumbura',
					'Naranpanawa West'
				]
			},
			{
				division: 'Kandy Four Gravets & Gangawata Korale',
				GSDivisions: [
					'Boowelikada',
					'Thalwatta',
					'Lewella',
					'Aruppala West',
					'Aruppala East',
					'Nittawela',
					'Siyambalagasthenna',
					'Mawilmada',
					'Watapuluwa',
					'Watapuluwa West',
					'Watapuluwa South',
					'Mahaweli Uyana',
					'Nuwara Dodanwala',
					'Aniwatta West',
					'Aniwatta East',
					'Asgiriya',
					'Bahirawa Kanda',
					'Mapanawathura',
					'Wattaranthenna',
					'Mahaiyawa',
					'Poornawatta West',
					'Poorna Watta East',
					'Heeressagala',
					'Mulgampala',
					'Udabowala',
					'Bowala',
					'Ogastawatta',
					'Bowalawatta',
					'Palle Peradeniya',
					'Uda Peradeniya',
					'Pitakanda Gama',
					'Senkadagala',
					'Ampitiya North',
					'Ampitiya South',
					'Malwatta',
					'Katukele',
					'Katukele West',
					'Mahanuwara',
					'Ihala Katukele',
					'Gatambe',
					'Welata',
					'Deiyannewela',
					'Nagasthenna',
					'Hanthana Place',
					'Bogambara',
					'Suduhumpala East',
					'Suduhumpala West',
					'Hindagala',
					'Mahakanda',
					'Ampitiya Udagama North',
					'Ampitiya Udagama South',
					'Ampitiya Pallegama',
					'Meddegama',
					'Ulpathakumbura',
					'Wewathenna',
					'Thennekumbura',
					'Gurudeniya East',
					'Gurudeniya Dambawela',
					'Gurudeniya West',
					'Maligathenna',
					'Lewla',
					'Ketawala',
					'Pahala Eriyagama',
					'Godagandeniya'
				]
			},
			{
				division: 'Harispattuwa',
				GSDivisions: [
					'Waratenna',
					'Yatihalagala Pallegama',
					'Kumburegedara',
					'Udadoolwala',
					'Pahala Doolwala',
					'Bulathgolla',
					'Yatihalagala Udagama',
					'Seewaleekanda',
					'Kulugammana',
					'Kurundugahamada',
					'Dadahogama',
					'Mapamadulla',
					'Hapugoda',
					'Ranawana West',
					'Ranawana East',
					'Udabokalawela',
					'Pallebokalawela',
					'Katugasthota',
					'Etamurungagoda',
					'Yatiwawala',
					'Inigala',
					'Uduwawala West',
					'Uduwawala North',
					'Uduwawala East',
					'Polwatta',
					'Wegiriya',
					'Rathmale',
					'Kondadeniya',
					'Senarathgama South',
					'Senarathgama North',
					'Uguressapitiya',
					'Uggalla',
					'Madapathagama',
					'Gohagoda',
					'Narangaskumbura',
					'Banwelgolla',
					'Pallemulla',
					'Udamulla',
					'Hal Pallegama',
					'Haloluwa',
					'Hamangoda North',
					'Hamangoda South',
					'Bogahakanda',
					'Malagammana',
					'Nugawela',
					'Embulpure',
					'Batuambe',
					'Hiriyalagammana',
					'Kurunduwatta',
					'Yahalathenna Kanda',
					'Mahatenna',
					'Yahalathenna West',
					'Ruwanpuraya',
					'Thittapajjala',
					'Thittapajjala North',
					'Rajapihilla',
					'Endaruthenna',
					'Ulladupitiya East',
					'Ulladupitiya West',
					'Gonigoda',
					'Gonigoda-Palkumbura',
					'Viguhumpola',
					'Arambegama',
					'Aladeniya',
					'Hedeniya',
					'Narangoda',
					'Kurundugolla',
					'Palkumbura',
					'Rajasinhagama',
					'Ihala Karanduwawala]',
					'Pahala Karanduwawala',
					'Owathenna',
					'Attaragama',
					'Attaragama East',
					'Attaragama South',
					'Bothota',
					'Medawala',
					'Angoda',
					'Dembaralawa',
					'Doranegama',
					'Amuwandeniya',
					'Ihagama',
					'Wathuwala',
					'Uyanwatta'
				]
			},
			{
				division: 'Hatharaliyadda',
				GSDivisions: [
					'Welivita Ihalagama',
					'Pelena Pahalagama',
					'Welivita Pahalagama',
					'Aluthgama Ihala',
					'Walpalagolla South',
					'Walpalagolla East',
					'Meegasthenna',
					'Paragoda',
					'Welagama',
					'Damunupola',
					'Lechchimimenila',
					'Kolugala Pahala',
					'Walpalagolla North',
					'Yaggala',
					'Kanakkarapola North',
					'Pelena',
					'Welivita Pahalagama South',
					'Alagalla Ihala',
					'Ilpemada',
					'Sivurupitiya',
					'Welivita Ihalagama North',
					'Imbulethenna',
					'Kithuldora',
					'Alagalla Pahalagama',
					'Aludeniya South',
					'Polwatta Ihalagama',
					'Dedunupitiya Ihala',
					'Amboruwa',
					'Weligodapola',
					'Aludeniya North',
					'Aluthgama Pahala',
					'Pallepola',
					'Dehideniya Madige',
					'Kalotuwawa',
					'Kolugala',
					'Andiyathenna',
					'Polwatta',
					'Avulbodale',
					'Mudagammana',
					'Pattapola Ihalagama',
					'Dedunupitiya Pahalagama',
					'Rangamuwa',
					'Hatharaliyadda',
					'Dunkumbura',
					'Narangaspitiya',
					'Mawathagama',
					'Ambawa',
					'Godathale',
					'Handabowa',
					'Alakolamaditta',
					'Eramuduliyadda',
					'Muruddeniya',
					'Kandemeeya',
					'Nikathenna',
					'Pattapola Pahala',
					'Kanakkarapola South',
					'Galdola'
				]
			},
			{
				division: 'Yatinuwara',
				GSDivisions: [
					'Bulumulla',
					'Pilapitiya',
					'Sooriyagoda',
					'Karuwalawatta',
					'Kiribathkumbura East',
					'Kiribathkumbura West',
					'Edanduwawa East',
					'Edanduwawa West',
					'Gannoruwa East',
					'Kendakaduwa',
					'Gannoruwa West',
					'Gannoruwa Central',
					'Pelawa Pahalagama',
					'Pelawa Ihalagama',
					'Pelawa Ihala Meda',
					'Yahalathenna',
					'Kobbekaduwa',
					'Ihala Kobbekaduwa',
					'Dehigama East',
					'Dehigama North',
					'Dehigama South',
					'Mangalagama',
					'Diyapalagoda',
					'Moladanda',
					'Malgammana',
					'Ranawana',
					'Uda Eriyagama East',
					'Uda Eriyagama West]',
					'Dehideniya East',
					'Dehideniya West',
					'Ihala Dodamwala',
					'Pahala Dodamwala',
					'Wathurakumbura',
					'Gurugama',
					'Dehianga North',
					'Dehianga South',
					'Danthure',
					'Munwathugoda',
					'Siyambalagoda',
					'Aranbegama East',
					'Arambegama West',
					'Embilmeegama North',
					'Embilmeegama South',
					'Urapola',
					'Kurunduwatta',
					'Kudaoya',
					'Govindala',
					'Pilimathalawa',
					'Ilukwatta',
					'Haliyadda',
					'Kotabogoda',
					'Madarangoda',
					'Udawela Nadithalawa',
					'Udawela Pallemaditta',
					'Udawela Pahalagama',
					'Giragama',
					'Parakatawella',
					'Imbulmalgama',
					'Yatigammana',
					'Pahala Yatigammana',
					'Pottepitiya',
					'Thismada',
					'Kirimetiya Watta',
					'Ihala Alagalla',
					'Godigamuwa',
					'Gondeniya',
					'Alagalla Watta',
					'Amunupura',
					'Weralugolla',
					'Moragolla Mahakanda',
					'Mudaliwatta',
					'Pahala Mudaliwatta',
					'Madiligama',
					'Udarathmeewala',
					'Pahala Rathmeewala',
					'Balana',
					'Motana Dekinda',
					'Mamudawala',
					'Ketakumbura',
					'Maligathenna',
					'Kadawathgama',
					'Kadugannawa Town',
					'Walgowwagoda',
					'Kavudupana',
					'Kandangama North',
					'Kandangama South',
					'Panabokka',
					'Walgampaya',
					'Bathgoda',
					'Doluwa East',
					'Doluwa West',
					'Kotaligoda North',
					'Kotaligoda South',
					'Menikdiwela',
					'Deldeniya'
				]
			},
			{
				division: 'Udunuwara',
				GSDivisions: [
					'Gangoda',
					'Gangoda South',
					'Gangoda North',
					'Thalawaththa',
					'Werellamana',
					'Boyagama',
					'Rajagiriya',
					'Hendeniya West',
					'Hendeniya East',
					'Yalegoda East',
					'Yalegoda West',
					'Handessa',
					'Naranwala',
					'Alapalawala East',
					'Alapalawala West',
					'Angunawala East',
					'Angunawala West',
					'Sangabogama',
					'Penideniya',
					'Meewathura',
					'Karamada South',
					'New Peradeniya',
					'Godapola East',
					'Godapola West',
					'Palle Aludeniya',
					'Pethiyagoda East',
					'Pethiyagoda West',
					'Meewaladeniya',
					'Ihala Pethiyagoda',
					'Muruthagahamula',
					'Dehipagoda West',
					'Dehipagoda East',
					'Gelioya',
					'New Elpitiya North',
					'Weligalla',
					'Uda Aludeniya',
					'Pitawalawatta',
					'Polgahaanga',
					'Delgahapitiya',
					'Palkumbura',
					'Wegiriya West',
					'Wegiriya East',
					'Thalawathura',
					'Lunugama',
					'Hondiyadeniya',
					'Eladhetta East',
					'Eladhetha West',
					'Arattana',
					'Davulagala',
					'Boowelikada',
					'Ambarapola',
					'Daskara',
					'Hathnagoda',
					'Bambaradeniya',
					'Rangoda',
					'Wathupola',
					'Ganhatha',
					'Werawala West',
					'Ambagasthenna',
					'Werawala East',
					'Embakka',
					'Meddegoda',
					'Siyambalagoda',
					'Rangama',
					'Hiyarapitiya',
					'Arawwawela',
					'Imbuldeniya',
					'Heeyawala',
					'Walgama',
					'Rabbegamuwa North',
					'Rabbegamuwa South',
					'Gadaladeniya South',
					'Pamunuwa East',
					'Pamunuwa West',
					'Deliwala',
					'Warakagoda',
					'Hepana',
					'Hiddavulla West',
					'Gadaladeniya North',
					'Kiriwavula West',
					'Ganguldeniya',
					'Pilapitiya',
					'Dihitideniya',
					'Appallagoda East',
					'Appallagoda West',
					'Kotagaloluwa',
					'Deldeniya',
					'Viharagama',
					'Welamboda',
					'Liyangahawaththa',
					'Maweekumbura North',
					'Maveekumbura South',
					'Ambanwala',
					'Kooradeniya',
					'Manikkawa',
					'Nikahetiya',
					'Wattappola',
					'Walagedara South',
					'Sadikkawatta',
					'Kovilakanda	  ',
					'Lagamuwa',
					'Belungala',
					'Aluthkanda',
					'Kurukuttala Ihala',
					'Pahala Kurukuttla',
					'Mathgamuwa',
					'Udagama',
					'Urulewaththa',
					'Aladuwaka',
					'Panabokka',
					'Karamada North',
					'Walagedara North',
					'Kiriwavula East',
					'Hiddavulla East',
					'Mampitiya',
					'Piligalla East',
					'Piligalla West',
					'Kamburadeniya',
					'New Elpitiya South',
					'Ketakumbura',
					'Batupitiya',
					'Dodandeniya',
					'Watadeniya',
					'Elpitikanda'
				]
			},
			{
				division: 'Doluwa',
				GSDivisions: [
					'Mulgama',
					'Pitawala',
					'Ududeniya',
					'Gurukele',
					'Nawa Nillamba',
					'Gurukele',
					'Nawa Gurukele',
					'Thumpelawaka',
					'Nillamba',
					'Masgolla',
					'Hunugala',
					'Thundeniya',
					'Kahawatta',
					'Gothatuwela',
					'Legumdeniya',
					'Panvilathenna',
					'Pambadeniya',
					'Naranvita',
					'Gampolawatta',
					'Atuwewatta',
					'Wewathenna',
					'Inguruwatta',
					'Orayanwatta',
					'Doluwa',
					'Godawela',
					'Megoda Kalugamuwa',
					'Ganegoda',
					'Haloya',
					'Wariyagala',
					'Galoya',
					'Millagahamula',
					'Pupuressa',
					'Rajathalawa'
				]
			},
			{
				division: 'Pathahewaheta',
				GSDivisions: [
					'Udawela Pallegama West',
					'Galthenna',
					'Moragolla',
					'Ankelipitiya',
					'Haputhale Pallegama',
					'Sriyagama',
					'Nugaliyadda Ihala',
					'Kapuliyadda West',
					'Letiyagolla',
					'Ethulgama South',
					'Ethulgama West',
					'Godalawela',
					'Narangasthenna',
					'Godamunna West',
					'Nugaliyadda Pahala',
					'Uduwela Udagama West',
					'Haragama',
					'Kapuliyadda East',
					'Oluwawatta',
					'Doolmure',
					'Ududeniya',
					'Hewavissa West',
					'Pothgoda',
					'Medadeniya',
					'Nilawala',
					'Elikewela',
					'Damunugolla',
					'Bopitiya',
					'Ududeniya Madihe',
					'Kethigannawela',
					'Marassana',
					'Galagoda',
					'Bolepa',
					'Unuvinna East',
					'Pathamailapitiya South',
					'Udamailapitiya North',
					'Pathamailapitiya North',
					'Godompitiya',
					'Ethulgama North',
					'Thalathuoya  East',
					'Haputhale Udagama',
					'Sigharagama',
					'Nehiniwela',
					'Pussathenna',
					'Batagalla',
					'Hippola',
					'Thalathuoya  West',
					'Pinnagolla',
					'Uduwela Pallegama East',
					'Ratemulla',
					'Pooliyadda',
					'Uduwela Pallegama South',
					'Medagama Pallegama',
					'Unuvinna West',
					'Hewavissa East',
					'Welegama',
					'Wathuliyadda',
					'Udawelawatta Colony',
					'Medagama Udagama',
					'Haputhale Egodagama',
					'Ethulgama East',
					'Udamailapitiya South',
					'Kiriwanagoda',
					'Uduwela Udagama East',
					'Bootawatta North',
					'Kossinna',
					'Bawlana',
					'Kandewela',
					'Godamunna East',
					'Monarangala',
					'Bootawatta South',
					'Meeruppa',
					'Kahambiliyawa'
				]
			},
			{
				division: 'Delthota',
				GSDivisions: [
					'Pattiyagama Pallegama',
					'Bopitiya Nagaraya',
					'Maussawa',
					'Nawaneliya',
					'Kotagepitiya',
					'Murapola West',
					'Pattiyagama Gabadama North',
					'Pattiyagama Udagama',
					'Bawlanawatta Janapadaya',
					'Kolambissa West',
					'Kandegama',
					'Perawatta West',
					'Suduwella',
					'Palugama',
					'Galaha',
					'Udadelthota',
					'Perawatta East',
					'Greatweliya',
					'Kirawanaketiya',
					'Medakekila',
					'Karagaskada South',
					'Pattiyagama Gabadama South',
					'Kolambissa East',
					'Wadiyagoda',
					'Watakepotha',
					'Murapola East',
					'Wanahapuwa',
					'Karagaskada North',
					'Gonangoda'
				]
			},
			{
				division: 'Udapalatha',
				GSDivisions: [
					'Illawathura',
					'Gampola East',
					'Bothalapitiya',
					'Gampola West',
					'Polkumbura',
					'Eragoda',
					'Kurukude',
					'Kudamake',
					'Jayamalapuraya',
					'Godagama',
					'Sinhapitiya South',
					'Kahatapitiya',
					'Ilangawatta',
					'Unambuwa',
					'Mount Temple',
					'Kirinda',
					'Galgediyawa',
					'Udovita',
					'Rathmalkaduwa',
					'Sinhapitiya North',
					'Hapugaspitiya',
					'Keerapane',
					'Ranawala',
					'Bowala',
					'Egoda Kalugamuwa',
					'Angammana East',
					'Angammana West',
					'Amunupuraya',
					'Delpitiya',
					'Nawa Devita',
					'Pallegama',
					'Amuhena',
					'Wattehena',
					'Udagama',
					'Millagaspitiya',
					'Ihalagama',
					'Hunukotugama',
					'Pussellawa',
					'Wahugapitiya',
					'Paradeka',
					'Pussellawagama',
					'Doragala',
					'Dunukeulla',
					'Wanahapuwa',
					'Galatha',
					'Kekulanda',
					'Mawathura',
					'Weliganga',
					'Kalugalhinna'
				]
			},
			{
				division: 'Ganga Ihala Korale',
				GSDivisions: [
					'Galpaya',
					'Herakola',
					'Pitakanda',
					'Mallwattagama',
					'Karagala',
					'Ethgala  East',
					'Alugolla',
					'Pellapitiya North',
					'Ulapane North',
					'Miyanagolla',
					'Maligapurana',
					'Watakedeniya',
					'Giraulla',
					'Ulapane South',
					'Uduwella',
					'Patithalawa',
					'Kelly Group',
					'Rakshawa',
					'Yatapana',
					'Kohowala',
					'Polmalagama',
					'Pellapitiya South',
					'Wallahagoda',
					'Udahenthenna',
					'Gamunupura',
					'Udagama',
					'Thembiligala',
					'Ethgala North',
					'Ethgala West',
					'Sinhapura',
					'Gampolawela'
				]
			},
			{
				division: 'Pasbage Korale',
				GSDivisions: [
					'Pallegama',
					'Mapakanda North',
					'Warakawa',
					'Nawalapitiya East',
					'Bawwagama',
					'Nawalapitiya South',
					'Imbulpitiya',
					'Dekinda',
					'Balanthota north',
					'Kendopitiya',
					'Balanthota South',
					'Westhole',
					'Hydry',
					'Wewegama',
					'Inguruoya South',
					'Inguruoya North',
					'Weligodawatta',
					'Kadiyanlena',
					'Mapakanda South',
					'Dandubendiruppa',
					'Phala Rambukpitiya',
					'Penithuduwa',
					'Nawalapitiya West',
					'Uda Rambukpitiya',
					'Aluthgama',
					'Weligampala',
					'Karahandungala',
					'Nawalapitiya North',
					'Greenwood'
				]
			}
		]
	},
	{
		district: 'Colombo',
		DSDivisions: [
			{
				division: 'Colombo',
				GSDivisions: [
					'Aluthkade East',
					'Aluthkade West',
					'Aluthmawatha',
					'Grandpass North',
					'Grandpass South',
					'Ibbanwala',
					'Jinthupitiya',
					'Keselwatta',
					'Kettarama',
					'Pettah',
					'Kochchikade North',
					'Lunupokuna',
					'Madampitiya',
					'Maligakanda',
					'Maligawatta West',
					'Maradana',
					'Massangar Street',
					'Mattakkuliya',
					'Panchikawatta',
					'New Bazaar',
					'Suduwella',
					'Wekanda',
					'Kotahena West',
					'Maligawatta East',
					'Sammanthranapura',
					'Hunupitiya',
					'Slave Island',
					'Fort',
					'Bloemendhal',
					'Galle Face',
					'Nawagampura',
					'Kotahena East',
					'Mahawatta',
					'Modara',
					'Kochchikade South'
				]
			},
			{
				division: 'Dehiwala-Mount Lavinia',
				GSDivisions: [
					'Kalubowila',
					'Nedimala',
					'Udyanaya',
					'Vilawala',
					'Dutugemunu',
					'Kohuwala',
					'Galwala',
					'Hathbodhiya',
					'Sri Saranankara',
					'Karagampitiya',
					'Malwatta',
					'Kawdana East',
					'Dehiwala East',
					'Dehiwala West',
					'Jayathilaka'
				]
			},
			{
				division: 'Homagama',
				GSDivisions: [
					'Niyadagala',
					'Brahmanagama',
					'Heraliyawala',
					'Siddamulla South',
					'Siddamulla North',
					'Mattegoda West',
					'Mattegoda East',
					'Habarakada South',
					'Kithulavila',
					'Panagoda Town',
					'Kahathuduwa North',
					'Pitipana South',
					'Watareka South',
					'Moonamale - Yakahaluwa',
					'Uduwana',
					'Hiripitiya',
					'Prasannapura',
					'Kurunduwatta',
					'Magammana West',
					'Mawathagama',
					'Mullegama North',
					'Galavilawatta North',
					'Mambulgoda',
					'Kahathuduwa East',
					'Batawala',
					'Homagama North',
					'Kithulhena',
					'Panagoda East',
					'Kahathuduwa South',
					'Katuwana',
					'Pitipana Town',
					'Habarakada Watta',
					'Kandhanawatta',
					'Kudamaduwa',
					'Diyagama West',
					'Henpita',
					'Rilawala',
					'Deepangoda',
					'Suwapubudugama',
					'Nawalamulla',
					'Meegasmulla',
					'Kiriwattuduwa North',
					'Ovitigama',
					'Habarakada North',
					'Mullegama South',
					'Sangarama',
					'Siyambalagoda South',
					'Meegoda North',
					'Panagoda West',
					'Diyagama East',
					'Weniwelkola',
					'Mattegoda Central B',
					'Palagama',
					'Atigala East',
					'Wethara',
					'Undurugoda',
					'Henawatta',
					'Gehenuwala',
					'Kiriberiyakele',
					'Galavilawatta South',
					'Homagama South',
					'Kirigampamunuwa',
					'Pitipana North',
					'Homagama East',
					'Homagama West',
					'Mattegoda Central "A"',
					'Meegoda South',
					'Panaluwa',
					'Watareka North',
					'Jalthara',
					'Walpita',
					'Godagama North',
					'Godagama South',
					'Dolahena',
					'Homagama Town',
					'Magammana East',
					'Siyambalagoda North',
					'Ambalangoda',
					'Kahathuduwa West',
					'Kiriwattuduwa South',
					'Atigala West'
				]
			},
			{
				division: 'Kaduwela',
				GSDivisions: [
					'Nawagamuwa',
					'Ranala',
					'Nawagamuwa South',
					'Ihala Bomiriya',
					'Wekewatta',
					'Pahala Bomiriya',
					'Pahala Bomiriya B',
					'Kothalawala',
					'Kaduwela',
					'Hewagama'
				]
			},
			{
				division: 'Kesbewa',
				GSDivisions: [
					'Thumbovila South',
					'Morenda',
					'Batakettara South',
					'Boralesgamuwa East A',
					'Boralesgamuwa West C',
					'Divulpitiya East',
					'Divulpitiya West',
					'Suwarapola West',
					'Hedigama',
					'Polhena',
					'Nivungama',
					'Makandana West',
					'Kesbewa South',
					'Horathuduwa',
					'Mampe North',
					'Vishwakalawa',
					'Mampe South',
					'Mampe East',
					'Bokundara',
					'Bodhirajapura',
					'Wewala East',
					'Katuwawala South',
					'Kaliyammahara',
					'Niwanthidiya',
					'Bangalawatta',
					'Pelenwatta North',
					'Pelenwatta West',
					'Erewwala North',
					'Mahalwarawa',
					'Makuludoowa',
					'Paligedara',
					'Honnanthara South',
					'Batuwandara South',
					'Jamburaliya',
					'Regidel Watta',
					'Mampe West',
					'Boralesgamuwa West A',
					'Boralesgamuwa West B',
					'Pepiliyana West',
					'Erewwala East',
					'Pepiliyana East',
					'Boralesgamuwa East B',
					'Rattanapitiya',
					'Egodawatta',
					'Bellanvila',
					'Mavittara North',
					'Delthara East',
					'Delthara West',
					'Dampe',
					'Madapatha',
					'Wewala West',
					'Batakettara North',
					'Makandana East',
					'Halpita',
					'Kesbewa East',
					'Suwarapola East',
					'Kesbewa North',
					'Kolamunna',
					'Thumbovila West',
					'Thumbovila North',
					'Werahera North',
					'Werahera South',
					'Katuwawala North',
					'Neelammahara',
					'Erewwala West',
					'Rathmaldeniya',
					'Pelenwatta East',
					'Gorakapitiya',
					'Nampamunuwa',
					'Honnanthara North',
					'Mavittara South',
					'Batuwandara North',
					'Kahapola'
				]
			},
			{
				division: 'Kolonnawa',
				GSDivisions: [
					'Mulleriyawa North',
					'Ambathale',
					'Udumulla North',
					'Udumulla South',
					'Maligagodella',
					'Rajasinghagama',
					'Himbutana West',
					'Mulleriyawa South',
					'Himbutana East',
					'Malgama',
					'Kelanimulla',
					'Belagama',
					'Kotikawatta East',
					'Malpura',
					'Kotikawatta West',
					'Gothatuwa New Town',
					'Dodamgahahena',
					'Maha Buthgamuwa A',
					'Kuda Buthgamuwa',
					'Batalandahena',
					'Maha Buthgamuwa B',
					'Maha Buthgamuwa C',
					'Wennawatta',
					'Kiththampahuwa',
					'Welewaththa',
					'Kotuvila',
					'Sedawatta',
					'Veheragoda',
					'Halmulla',
					'Wathulla',
					'Meethotamulla',
					'Orugodawatta',
					'Kuriniyawatta',
					'Wellampitiya',
					'Dahampura',
					'Kolonnawa',
					'Salamulla',
					'Singhapura',
					'Gajabapura',
					'Wijayapura',
					'Gothatuwa',
					'Megoda Kolonnawa',
					'Madinnagoda',
					'Kajugahawatta',
					'Bopeththa',
					'Elhena'
				]
			},
			{
				division: 'Maharagama',
				GSDivisions: [
					'Kalalgoda',
					'Thalawathugoda West',
					'Thalawathugoda East',
					'Kottawa South',
					'Kottawa East',
					'Kottawa Town',
					'Kottawa North',
					'Kottawa West',
					'Liyanagoda',
					'Rukmale West',
					'Rukmale East A',
					'Rukmale East B',
					'Malapalla East',
					'Makumbura North',
					'Malapalla West',
					'Makumbura South',
					'Mirihana North',
					'Mirihana South',
					'Madiwela',
					'Pragathipura',
					'Thalapathpitiya',
					'Udahamulla East',
					'Udahamulla West',
					'Gangodavila South B',
					'Wijerama',
					'Jambugasmulla',
					'Navinna',
					'Pathiragoda',
					'Maharagama East',
					'Maharagama West',
					'Pamunuwa',
					'Dambahena',
					'Polwatta',
					'Depanama',
					'Maharagama Town',
					'Pannipitiya North',
					'Pannipitiya South',
					'Godigamuwa North',
					'Godigamuwa South',
					'Godigamuwa South B',
					'Wattegedara'
				]
			},
			{
				division: 'Moratuwa',
				GSDivisions: [
					'Angulana South',
					'Angulana North',
					'Dahampura',
					'Egoda Uyana Central',
					'Egoda Uyana North',
					'Egoda Uyana South',
					'Molpe',
					'Indibedda East',
					'Indibedda West',
					'Kadalana',
					'Kaldemulla',
					'Katubedda',
					'Katukurunda North',
					'Katukurunda South',
					'Koralawella East',
					'Koralawella North',
					'Koralawella West',
					'Kuduwamulla',
					'Lakshapathiya Central',
					'Lakshapathiya North',
					'Lakshapathiya South',
					'Moratuwella West',
					'Moratuwella North',
					'Rawathawatta East',
					'Rawathawatta South',
					'Rawathawatta West',
					'Soysapura North',
					'Soysapura South',
					'Koralawella South',
					'Thelawala South',
					'Thelawala North',
					'Uswatta',
					'Uyana North',
					'Uyana South',
					'Villorawatta East',
					'Villorawatta West',
					'Borupana',
					'Idama',
					'Moratumulla North',
					'Moratumwella South',
					'Moratumulla East',
					'Moratumulla West'
				]
			},
			{
				division: 'Padukka',
				GSDivisions: [
					'Kahawala',
					'Yatawathura',
					'Galagedara South',
					'Pitumpe North',
					'Liyanwala',
					'Galagedara East',
					'Beliattavila',
					'Waga North',
					'Waga West',
					'Arukwatta South',
					'Ihala Bope',
					'Angampitiya',
					'Gurulana',
					'Uggalla',
					'Udumulla',
					'Miriyagalla',
					'Thummodara',
					'Pahala Padukka',
					'Padukka',
					'Poregedara',
					'Arukwatta North',
					'Madulawa North',
					'Waga South',
					'Pinnawala South',
					'Weragala',
					'Horagala East',
					'Madulawa South',
					'Wewelpanawa',
					'Ganegoda',
					'Pahala Bope',
					'Pinnawala North',
					'Kurugala',
					'Malagala',
					'Horagala West',
					'Beruketiya',
					'Udagama',
					'Dabora',
					'Mahingala',
					'Galagedara North',
					'Dampe',
					'Horakandawala',
					'Waga East',
					'Halpe',
					'Siyambalawa',
					'Angamuwa',
					'Pitumpe South'
				]
			},
			{
				division: 'Ratmalana',
				GSDivisions: [
					'Mount Lavinia',
					'Kawdana West',
					'Watarappala',
					'Wathumulla',
					'Katukurunduwatta',
					'Attidiya North',
					'Attidiya South',
					'Piriwena',
					'Wedikanda',
					'Vihara',
					'Rathmalana West',
					'Rathmalana East',
					'Kandawala'
				]
			},
			{
				division: 'Hanwella',
				GSDivisions: [
					'Kanampella East',
					'Kanampella West',
					'Thawalgoda',
					'Muruthagama',
					'Pahala Kosgama East',
					'Salawa',
					'Pahala Kosagama West',
					'Ihala Kosgama North',
					'Aluth Ambalama',
					'Ihala Kosgama South',
					'Miriswatta',
					'Eswatta North',
					'Hingurala',
					'Manakada',
					'Eswatta South',
					'Kadugoada North',
					'Kadugoda South',
					'Puwakpitiya',
					'Kiriwandala North',
					'Puwakpitiya South',
					'Egodagama',
					'Kiriwandala South',
					'Weragolla South',
					'Seethawaka',
					'Ukwatta',
					'Kotahera',
					'Aradhana Kanda',
					'Seethagama',
					'Agra place',
					'Bollathawa',
					'Akaravita',
					'Kahatapitiya',
					'Gira Imbula',
					'Kalu Aggala',
					'Suduwella',
					'Mawalgama',
					'Diddeniya North',
					'Diddeniya South',
					'Brandigampala',
					'Mabula',
					'Kahahena',
					'Welikanna',
					'Pagnagula',
					'Ilukovita',
					'Ihala Hanwella North',
					'Pelpola',
					'Pahathgama',
					'Hanwella Town',
					'Ihala Hanwella South',
					'Jayaweeragoda',
					'Thunnana East',
					'Thunnana West',
					'Mawathagama East',
					'Kudakanda',
					'Pahala Hanwella',
					'Walauwathta',
					'Weragolla North',
					'Avissawella',
					'Kudagama',
					'Weralupitiya',
					'Niripola',
					'Neluwattuduwa',
					'Elamalawala',
					'Koswatta',
					'Digana',
					'Mawathagama West',
					'Koodaluvila',
					'Lahirugama'
				]
			},
			{
				division: 'Sri Jayawardanapura Kotte',
				GSDivisions: [
					'Gangodavila North',
					'Nawala West',
					'Gangodavila East',
					'Obesekarapura',
					'Welikada East',
					'Ethulkotte',
					'Rajagiriya',
					'Koswatta',
					'Welikada West',
					'Welikada North',
					'Nugegoda',
					'Pagoda',
					'Nugegoda West',
					'Pagoda East',
					'Nawala  East',
					'Ethulkotte West',
					'Pitakotte West',
					'Pitakotte',
					'Pitakotte East',
					'Gangodavila South'
				]
			},
			{
				division: 'Thimbirigasyaya',
				GSDivisions: [
					'Bambalapitiya',
					'Borella North',
					'Borella South',
					'Dematagoda',
					'Gothamipura',
					'Havelock Town',
					'Kirula',
					'Kirulapone',
					'Kollupitiya',
					'Kuppiyawatta East',
					'Kuppiyawatta West',
					'Kurunduwatta',
					'Milagiriya',
					'Narahenpita',
					'Wellawatta North',
					'Pamankada West',
					'Pamankada East',
					'Wanathamulla',
					'Wellawatta South',
					'Thimbirigasyaya'
				]
			}
		]
	},
	{
		district: 'Jaffna',
		DSDivisions: [
			{
				division: 'Delft',
				GSDivisions: [
					'Delft West',
					'Delft South',
					'Delft Centre West',
					'Delft Centre',
					'Delft Center East',
					'Delft East'
				]
			},
			{
				division: 'Island North (Kayts)',
				GSDivisions: [
					'Analativu North',
					'Analaitivu South',
					'Kayts',
					'Paruthiyadaippu',
					'Eluvaitivu',
					'Karampon',
					'Karampon East',
					'Karampon South East',
					'Karampon West',
					'Naranthanai North',
					'Naranthanai North West',
					'Naranthanai',
					'Naranthanai South',
					'Suruvil',
					'Puliyankoodal'
				]
			},
			{
				division: 'Island South (Velanai)',
				GSDivisions: [
					'Velanai South East',
					'Velanai center west',
					'Pungudutivu North East',
					'Pungudutivu East',
					'Velanai North East',
					'Nainativu North',
					'Pungudutivu Centre west',
					'Pungudutivu East South',
					'Mankumpan',
					'Velanai West',
					'Mandaitivu East',
					'Mandaitivu West',
					'Pungudutivu Centre North',
					'Pungudutivu South West',
					'Allaipiddy',
					'Velanai Center East',
					'Saravanai West',
					'Velanai South',
					'Saravanai East',
					'Mandaitivu South',
					'Nainativu Center',
					'Nainativu South',
					'Pungudutivu South',
					'Velanai North',
					'Velanai East',
					'Pungudutivu South East',
					'Pungudutivu North',
					'Pungudutivu Centre East',
					'Pungudutivu North West',
					'Pungudutivu West'
				]
			},
			{
				division: 'Jaffna',
				GSDivisions: [
					'Small Bazaar',
					'Fort',
					'Jaffna Town East',
					'Thirunagar',
					'Gurunagar East',
					'Eachchamoddai',
					'Gurunagar West',
					'Koddady',
					'Aththiady',
					'Navanthurai North',
					'Jaffna Town West',
					'Sirampiyady',
					'Grand Bazaar',
					'Columbuthurai West',
					'Passaiyoor East',
					'Passaiyoor West',
					'Vannarpannai',
					'Navanthurai South',
					'Reclamation West',
					'Moor Street North',
					'New Moor Street',
					'Chundikuly North',
					'Moor Street South',
					'Nedunkulam',
					'Columbuthurai East',
					'Reclamation East',
					'Chundikuly South',
					'Maruthady'
				]
			},
			{
				division: 'Karainagar',
				GSDivisions: [
					'Karainagar West',
					'Karainagar Centre',
					'Karainagar East',
					'Karainagar South West',
					'Karainagar North',
					'Karainagar North East',
					'Karainagar South',
					'Karainagar South East',
					'Karainagar North West'
				]
			},
			{
				division: 'Nallur',
				GSDivisions: [
					'Ariyalai South West(East)',
					'Ariyalai East',
					'Ariyalai Center West',
					'Ariyalai North West',
					'Ariyalai South West',
					'Ariyalai Center South',
					'Iyanar Kovilady',
					'Vannarpannai North',
					'Vannarponnai North West',
					'Vannarpannai North East ( Part )',
					'Ariyalai Centre North',
					'Ariyalai Centre',
					'Vannarponnai N.E.(South)',
					'Kantharmadam North West',
					'Kantharmadam North East (Part)',
					'Kantharmadam South West',
					'Kantharmadam South East',
					'Nallur North',
					'Nallur Rajadaniya',
					'Nallur South',
					'Sangiliyanthoppu',
					'Thirunelvelly West',
					'Thirunelvely Centre South',
					'Thirunelvely  South East',
					'Thirunelve‍ly North East',
					'Thirunelvelly Centre North',
					'Kondavil North West',
					'Kondavil South West',
					'Kondavil Centre  West',
					'Kondavil Centre  East',
					'Kondavil North East',
					'Kondavil South East',
					'Kokuvil North East',
					'Kokuvil East',
					'Kokuvil South East',
					'Kokuvil North West',
					'Kokuvil West',
					'Kokuvil Centre East',
					'Kokuvil South West',
					'Kokuvil Centre West'
				]
			},
			{
				division: 'Thenmaradchi (Chavakachcheri)',
				GSDivisions: [
					'Kovilkudiiruppu',
					'Eluthumadduval South',
					'Kodikamam Centre',
					'Thavalai Iyattalai',
					'Varani Iyattalai',
					'Sarasalai North',
					'Kaithady South',
					'Ketpely',
					'Kaithady Navatkuli',
					'Navatkuli East',
					'Sarasalai South',
					'Meesalai West',
					'Palavi',
					'Chandrapuram',
					'Kaithady West',
					'Mirusuvil South',
					'Meesalai North',
					'Nunavil Centre',
					'Ramavil',
					'Karambaikurichchi',
					'Madduvil Nunavil',
					'Mirusuvil North',
					'Idaikkurichchi',
					'Usan',
					'Kodikamam South',
					'Madduvil North',
					'Karampagam',
					'Kaithady North',
					'Kovilakkandy',
					'Thanankalappu',
					'Masery',
					'Kudamiyan',
					'Navatkuli West',
					'Sangaththanai',
					'Manthuvil West',
					'Kachchai',
					'Eluthumadduval North',
					'Vidaththtpalai',
					'Vellampokkadi',
					'Nunavil West',
					'Kaithady Nunavil',
					'Madduvil East',
					'Kalvayal',
					'Then Madduvil',
					'Maravanpulo',
					'Kodikamam North',
					'Chavakachcheri Town',
					'Varani North',
					'Kaithady East',
					'Chavakachcheri North',
					'Manduvil',
					'Nunavil East',
					'Madduvil Centre',
					'Meesalai East',
					'Allarai',
					'Navatkadu',
					'Manthuvil East',
					'Manthuvil North',
					'Kaithady Centre',
					'Kaithady South East'
				]
			},
			{
				division: 'Vadamaradchi North (Point Pedro) ',
				GSDivisions: [
					'Thondamanaru South',
					'Thondamanaru North',
					'Kerudavil South',
					'Kerudavil North',
					'Kerudavil East',
					'Valvettithurai North West',
					'Valvettiturai North Centre',
					'Valvettiturai North East',
					'Valvettithurai South West',
					'Valvettiturai South East',
					'Polikandy West',
					'Polikandy East',
					'Polikandy South',
					'Alvai West',
					'Alvai North West',
					'Alvai North Centre',
					'Viyaparimoolai',
					'Alvai North',
					'Point Pedro',
					'Point Pedro South',
					'Point Pedro East',
					'Thumpalai',
					'Thumpalai East',
					'Katkovalam',
					'Puloly North',
					'Puloly North East',
					'Puloly Centre',
					'Puloly West',
					'Puloly South West',
					'Puloly North West',
					'Puloly East',
					'Puloly South',
					'Manthikai',
					'Vallipuram',
					'Thunnalai North'
				]
			},
			{
				division: 'Vadamaradchi East (Maruthnkerny) ',
				GSDivisions: [
					'Manalkadu',
					'Kudaththanai',
					'Kudathanai Karaiyoor',
					'Potpathy',
					'Ampan',
					'Nagar Kovil East',
					'Nagar Kovil South',
					'Nagar Kovil West',
					'Chempiyanpattu North',
					'Maruthankerny',
					'Vathirayan',
					'Aliyavalai',
					'Uduththurai',
					'Vetrilaikerny',
					'Mullian',
					'Pokkaruppu',
					'Chundikulam',
					'Chempianpattu South'
				]
			},
			{
				division: 'Vadamaradchy South-West (Karaveddy)',
				GSDivisions: [
					'Karaveddy West',
					'Karanavai North West',
					'Imayanan',
					'Karanavai',
					'Alvai South',
					'Karaveddy North',
					'Karaveddy Centre',
					'Samarabahu',
					'Kaddaiveli',
					'Nelliady',
					'Karanavai South',
					'Nelliady East',
					'Karaveddy East',
					'Alvai',
					'Uduppidy',
					'Aththai',
					'Thunnalai',
					'Thunnalai Centre',
					'Thunnalai West',
					'Karanavai West',
					'Thunnalai East',
					'Valvetty Centre',
					'Uduppidy South',
					'Karanavai East',
					'Karanavai Centre',
					'Karanavai North',
					'Alvai East',
					'Uduppidy North',
					'Maththony',
					'Karaveddy  South',
					'Nelliaddy North',
					'Thunnalai South',
					'Kapputhu',
					'Imayanan West',
					'Valvetty'
				]
			},
			{
				division: 'valikamam-East (kopayi) ',
				GSDivisions: [
					'Irupalai South',
					'Irupalai  East',
					'Kalviyankadu',
					'Kopay South',
					'Kopay Center',
					'Kopay North',
					'Urumpirai West',
					'Urumpirai North',
					'Urumpirai South',
					'Urumpirai East',
					'Urelu',
					'Neervely South',
					'Neervely North',
					'Neervely West',
					'Siruppiddy East',
					'Siruppiddy West',
					'Puttur West',
					'Puttur North',
					'Navakkiri',
					'Avaranhal East',
					'Avarankal West',
					'Puttur East',
					'Achchelu',
					'Watharawaththai',
					'Paththaimeny',
					'Thampalai Kathirippai',
					'Idaikaddu',
					'Valalai',
					'Atchuvely North',
					'Atchuvely South',
					'Atchuvely West'
				]
			},
			{
				division: 'Valikamam North (Tellipallai)',
				GSDivisions: [
					'Alaveddy West',
					'Kurumpasiddy East',
					'Thaiyiddy East',
					'Mallakam South',
					'Mallakam Centre',
					'Mallakam North',
					'Alavedy North',
					'Alaveddy Centre',
					'Alaveddy East',
					'Ganeswaram',
					'Alaveddy South',
					'Ilavalai North',
					'Ilavalai North West',
					'Vithahapuram',
					'Pannalai',
					'Kollankaladdy',
					'Naguleswaram',
					'Tellippalai East',
					'Tellippalai',
					'Thanthai Chelvapuram',
					'Maviddapuram',
					'Maviddapuram South',
					'Kankesanthurai West',
					'Kankesanthurai Centre',
					'Kankesanthurai South',
					'Palai Veemankamam North',
					'Palai Veemankamam South',
					'Kadduvan',
					'Kadduvan West',
					'Thenmaylai',
					'Kurumpasiddy',
					'Vasavilan East',
					'Vasavilan West',
					'Myliddy North',
					'Thaiyiddy North',
					'Thaiyiddy South',
					'Myliddythurai North',
					'Palaly South',
					'Palaly East',
					'Palaly North',
					'Thurkkapuram',
					'Varuththalaivilan',
					'Myliddithurai South',
					'Palaly North West',
					'Palaly West'
				]
			},
			{
				division: 'Valikamam South (Uduvil) ',
				GSDivisions: [
					'Earlalai South West',
					'Chunnakam Town South',
					'Inuvil North  East',
					'Uduvil North',
					'Earlalai South',
					'Punnalaikadduvan South',
					'Evinai',
					'Earlalai North',
					'Chunnakam  Town Centre',
					'Inuvil East',
					'Uduvil South  East',
					'Earlalai Centre',
					'Kuppilan  North',
					'Kuppilan South',
					'Inuvil South West',
					'Thavady South',
					'Sanguvely',
					'Punnalaikadduvan  North',
					'Earlalai East',
					'Chunnakam Town North',
					'Thavady East',
					'Earlalai West',
					'Uduvil Centre North',
					'Chunnakam  Town West',
					'Chunnakam Town East',
					'Uduvil South West',
					'Uduvil Centre',
					'Kantharodai',
					'Thavady North',
					'Inuvil West'
				]
			},
			{
				division: 'Valikamam South-West (Sandilipay)',
				GSDivisions: [
					'Suthumalai North',
					'Suthumalai South',
					'Savalkaddu',
					'Uyarappulam',
					'Ana‍icoddai',
					'Navali North',
					'Navaly East',
					'Navali South',
					'Manipay North',
					'Manipay East',
					'Manipay South',
					'Manipay West',
					'Sandilipay North',
					'Sandilipay Centre',
					'Sandilipay West',
					'Mahiyappiddy',
					'Vadaliyadaippu',
					'Pandaththarippu',
					'Piranpattu',
					'Si‍lalai North',
					'S‍ilalai South',
					'Mathagal East',
					'Mathagal South',
					'Mathagal West',
					'Periyavilan',
					'Maresankoodal',
					'Ilavalai',
					'Mullanai'
				]
			},
			{
				division: 'Valikamam West (Chankanai)',
				GSDivisions: [
					'Sithankerny',
					'Vadducoddai  West',
					'Araly West',
					'Chankanai West',
					'Chulipuram  Centre',
					'Chankanai Centre',
					'Araly Centre',
					'Panfippulam',
					'Chankanai South',
					'Chulipuram  East',
					'Vadducoddai North',
					'Sangarathai',
					'Arali North',
					'Vedducoddai South',
					'Araly East',
					'Vadducoddai South West (North)',
					'Araly South',
					'Tholpuram East',
					'Ponnalai',
					'Pannagam',
					'Chankanai East',
					'Moolai',
					'Tholpuram  West',
					'Vadducoddai East',
					'Chulipuram West'
				]
			}
		]
	}
]
