export const SET_USER = 'SET_USER'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'

export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR'

export const CLEAR_USER = 'CLEAR_USER'

export const SET_STUDENTS = 'SET_STUDENTS'
export const SET_STUDENTS_LOADING = 'SET_STUDENTS_LOADING'
export const SET_STUDENTS_ERRORS = 'SET_STUDENTS_ERRORS'
